### ISSUE TITLE
ImportError: cannot import name AsDataArray from xarray_dataclasses when importing squidpy after pip install nichecompass[all]

### ISSUE THREAD

**Issue by ASUQ** [Lotfollahi-lab/nichecompass#110]
After installing NicheCompass with all optional dependencies (`pip install nichecompass[all]`), the import of squidpy fails due to a missing symbol in `xarray_dataclasses`

Step to reproduce
1. Create a fresh virtual environment with Python 3.10
2. `pip install nichecompass[all]`
3. `import squidpy as sq`

Error
```
Traceback (most recent call last):
  File "/app/test.py", line 12, in <module>
    import squidpy as sq
  File "/env/lib/python3.10/site-packages/squidpy/__init__.py", line 6, in <module>
    from squidpy import datasets, gr, im, pl, read, tl
  File "/env/lib/python3.10/site-packages/squidpy/datasets/__init__.py", line 3, in <module>
    from squidpy.datasets._10x_datasets import visium, visium_hne_sdata
  File "/env/lib/python3.10/site-packages/squidpy/datasets/_10x_datasets.py", line 13, in <module>
    import spatialdata as sd
  File "/env/lib/python3.10/site-packages/spatialdata/__init__.py", line 57, in <module>
    from spatialdata import dataloader, datasets, models, transformations
  File "/env/lib/python3.10/site-packages/spatialdata/datasets.py", line 20, in <module>
    from spatialdata._core.operations.aggregate import aggregate
  File "/env/lib/python3.10/site-packages/spatialdata/_core/operations/aggregate.py", line 19, in <module>
    from spatialdata._core.operations._utils import _parse_element
  File "/env/lib/python3.10/site-packages/spatialdata/_core/operations/_utils.py", line 7, in <module>
    from spatialdata.models import SpatialElement
  File "/env/lib/python3.10/site-packages/spatialdata/models/__init__.py", line 19, in <module>
    from spatialdata.models.models import (
  File "/env/lib/python3.10/site-packages/spatialdata/models/models.py", line 17, in <module>
    from multiscale_spatial_image import to_multiscale
  File "/env/lib/python3.10/site-packages/multiscale_spatial_image/__init__.py", line 16, in <module>
    from .to_multiscale import Methods, to_multiscale, itk_image_to_multiscale
  File "/env/lib/python3.10/site-packages/multiscale_spatial_image/to_multiscale/__init__.py", line 1, in <module>
    from .to_multiscale import Methods, to_multiscale
  File "/env/lib/python3.10/site-packages/multiscale_spatial_image/to_multiscale/to_multiscale.py", line 4, in <module>
    from spatial_image import SpatialImage  # type: ignore
  File "/env/lib/python3.10/site-packages/spatial_image/__init__.py", line 14, in <module>
    from xarray_dataclasses import AsDataArray, Attr, Coordof, Data, Name
ImportError: cannot import name 'AsDataArray' from 'xarray_dataclasses' (/env/lib/python3.10/site-packages/xarray_dataclasses/__init__.py)

```

**Comment by ASUQ** [comment]
I tried all squidpy version to build the environment and found only squidpy v1.2.3 works with NicheCompass v0.2.4.
The Python environment was tested with three tutorial notebooks (Single Sample, Sample Integration, and Spatial Reference Mapping) and worked without any errors.

The logs and the script used are below.
[squidpy_test.log](https://github.com/user-attachments/files/21601960/squidpy_test.log)

squidpy_test.sh
```
#!/usr/bin/env bash
set -euo pipefail

TEMPLATE="Dockerfile.0.2.4_test"
if [[ ! -f "$TEMPLATE" ]]; then
  echo "Error: template '$TEMPLATE' not found in $(pwd)"
  exit 1
fi
if [[ ! -f test.py ]]; then
  echo "Error: 'test.py' not found in $(pwd)"
  exit 1
fi

echo "Fetching available Squidpy versions from PyPI…"
# Parse the comma-separated 'Available versions:' line
readarray -t VERSIONS < <(
  pip index versions squidpy 2>&1 \
    | grep 'Available versions:' \
    | sed 's/Available versions: //' \
    | tr ',' '\n' \
    | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' \
    | sort -rV
)

if (( ${#VERSIONS[@]} == 0 )); then
  echo "No Squidpy versions found. (Is your pip ≥ 20.3?)"
  exit 1
fi

echo "Found ${#VERSIONS[@]} versions:"
printf "  %s\n" "${VERSIONS[@]}"
echo

for ver in "${VERSIONS[@]}"; do
  tag="nichecompass_0.2.4_squidpy-test:${ver}"
  dockerfile="Dockerfile.0.2.4_squidpy_${ver}"
  echo "=== Testing Squidpy $ver (using $dockerfile) ==="

  # 1) Copy the template
  cp "$TEMPLATE" "$dockerfile"

  # 2) Replace the empty ARG with the specific version
  sed -i \
    -e 's|^ARG SQUIDPY_VERSION=".*"|ARG SQUIDPY_VERSION="'"$ver"'"|' \
    "$dockerfile"

  # 3) Build the image
  if docker build --no-cache -t "$tag" -f "$dockerfile" .
  then
    echo "build image succeeded for squidpy==$ver"
  else
    echo "build image FAILED for squidpy==$ver"
  fi

  # 4) Run your test.py (mounting the cwd into /app)
  if docker run --rm \
      -v "$PWD":/app \
      -w /app \
      "$tag" \
      python test.py
  then
    echo "import succeeded for squidpy==$ver"
  else
    echo "import FAILED for squidpy==$ver"
  fi

  echo
done

echo "All tests completed."
```

test.py
```
import os
import random
import warnings
from datetime import datetime

# import gdown
import anndata as ad
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc
import scipy.sparse as sp
import seaborn as sns
import squidpy as sq
from matplotlib import gridspec
from sklearn.preprocessing import MinMaxScaler

from nichecompass.models import NicheCompass
from nichecompass.utils import (add_gps_from_gp_dict_to_adata,
                                compute_communication_gp_network,
                                create_new_color_dict,
                                extract_gp_dict_from_mebocost_ms_interactions,
                                extract_gp_dict_from_nichenet_lrt_interactions,
                                extract_gp_dict_from_omnipath_lr_interactions,
                                filter_and_combine_gp_dict_gps_v2,
                                generate_enriched_gp_info_plots,
                                visualize_communication_gp_network)
```

Docker.0.2.4_test
```
FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

SHELL ["/bin/bash", "-c"]

ARG NICHECOMPASS_VERSION="0.2.4"
ARG SQUIDPY_VERSION=""
ARG TORCH="2.2.0"
ARG CUDA="cu121"

ENV VENV_PATH="/env"
ENV PATH="${VENV_PATH}/bin:${PATH}"
ENV NUMBA_CACHE_DIR=/tmp
ENV PYTHONNOUSERSITE=1
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential procps git python3 python3-dev python3-venv python3-pip python-is-python3 wget locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# get bedtools
# RUN wget -O /usr/bin/bedtools https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static && \
#     chmod a+x /usr/bin/bedtools

# install python packages
RUN python3 -m venv $VENV_PATH && \
    . "$VENV_PATH/bin/activate" && \
    pip install --upgrade pip wheel setuptools uv && \
    uv pip install "torch==${TORCH}+${CUDA}" --index-url "https://download.pytorch.org/whl/${CUDA}" && \
    uv pip install "numpy==1.*" pyg_lib torch_scatter torch_sparse -f "https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html" && \
    uv pip install papermill jupyterlab ipykernel gdown "nichecompass[all]==${NICHECOMPASS_VERSION}" "squidpy==${SQUIDPY_VERSION}"

COPY Dockerfile /docker/
RUN chmod -R 755 /docker
```

**Comment by ASUQ** [comment]
@FrancescaDr 
The Docker image is pushed in [quay.io](https://quay.io/repository/cellgeni/nichecompass).
I hope this image works for you.
